# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Azzida' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Azzida
  pod 'SideMenu', '~> 6.4.8'
  pod 'CarbonKit', '~> 2.3.1'
  pod 'IQKeyboardManagerSwift', '~> 6.5.5'
  pod 'Alamofire', '~> 4.9.1'
  pod 'Kingfisher', '~> 5.14.1'
  pod 'GooglePlaces', '~> 4.1.0'
  pod 'FBSDKCoreKit', '~> 7.1.1'
  pod 'FBSDKLoginKit', '~> 7.1.1'
  pod 'GoogleSignIn', '~> 5.0.2'
  pod 'Stripe'
  pod 'Firebase/Analytics', '~> 6.28.1'
  pod 'Firebase/DynamicLinks', '~> 6.28.1'
  pod 'Firebase/Messaging'
  pod 'SDWebImage', '~> 5.0'

  target 'AzzidaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AzzidaUITests' do
    # Pods for testing
  end

end
